import Head from "next/head";
import Avatar from "../components/Avatar";
import { ViewGridIcon } from "@heroicons/react/solid";
// import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <header className="flex justify-between w-full p-5 text-sm text-gray-700">
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          {/* Icon */}
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
          {/* Avatar */}
          <Avatar url="https://lh3.googleusercontent.com/ogw/ADea4I6rRrLqrgFY701efqSWBJ6mKOUVrTEsao5znFHv=s64-c-mo" />
        </div>
      </header>
      {/* Body */}
      {/* Footer */}
    </div>
  );
}
