import Head from "next/head";
import { useRouter } from "next/router";
import Avatar from "../components/Avatar";
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";

import Image from "next/image";
import Footer from "../components/Footer";
import { useRef } from "react";
import { route } from "next/dist/server/router";

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);

  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;
    if (!term) return;
    searchInputRef.current.value = "";
    router.push(`/search?term=${term}`);
  };

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.google.com/favicon.ico" />
      </Head>
      {/* Header */}
      <header className="flex justify-between w-full p-5 text-sm text-gray-700">
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          {/* Icon */}
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
          {/* Avatar */}
          <Avatar url="https://lh3.googleusercontent.com/ogw/ADea4I6rRrLqrgFY701efqSWBJ6mKOUVrTEsao5znFHv=s64-c-mo" />
        </div>
      </header>
      {/* Body */}
      <form className="flex flex-col items-center mt-44 flex-grow w-4/5">
        <Image
          src="https://www.google.com/logos/doodles/2021/get-vaccinated-wear-a-mask-save-lives-september-3-copy-6753651837109329-law.gif"
          width="350"
          height="170"
        />
        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg rounded-full border border-gray-200 px-5 py-3 items-center">
          <SearchIcon
            className="h-5 text-gray-500 max-w-md sm:max-w-xl md:max-w-xl lg:max-w-2xl"
            onClick={search}
          />
          <input
            ref={searchInputRef}
            type="text"
            className="focus:outline-none flex-grow px-4"
          />
          <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:flex-row sm:space-x-4 sm:space-y-0">
          <button onClick={search} className="btn">
            Google Search
          </button>
          <button className="btn">I'm Feeling Lucky</button>
        </div>
      </form>
      {/* Footer */}
      <Footer />
    </div>
  );
}
